name: Coverage

on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  pull_request:
    branches: 
      - master
jobs:
  coverage:
    name: Codecov
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.7.6'
    
    - name: get packages
      run: flutter pub get
    
    - name: Flutter Test
      run: flutter test --coverage --coverage-path ../coverage/lcov.info
      
    - name: Codecov GitHub Action
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
